steps:
  - label: ":docker: build docker image"
    command:
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

#  - label: ":cop::skin-tone-2: deploy check"
#    command: ".buildkite/steps/deploy-test.sh"
#    timeout: 90
#    agents:
#       queue: "testing"
#    artifact_paths:
#      - "proxy.log"
#      - "solana.log"
#      - "measurements.log"
#      - "evm_loader.log"
#      - "faucet.log"
#      - "airdropper.log"
#      - "indexer.log"

  - label: ":coverage: full test suite"
#    if: |
#        (build.pull_request.base_branch == "develop" && !build.pull_request.draft) ||
#        (build.source == "trigger_job" && build.env("NEON_EVM_FULL_TEST_SUITE") == "true")
    commands:
      - FULL_TEST_RESULT=$(docker-compose -f docker-compose-full-test-suite.yml up --no-log-prefix | (grep -oP "(?<=Passing - )\d+" || echo 0))
      - echo Full test passing - $${FULL_TEST_RESULT}
      - echo Full test threshold - $${FULL_TEST_THRESHOLD}
      - echo Check if $${FULL_TEST_RESULT} is greater or equeal $${FULL_TEST_THRESHOLD}
      - test $${FULL_TEST_RESULT} -ge $${FULL_TEST_THRESHOLD}
    env:
      FULL_TEST_THRESHOLD: 934

  - wait

  - label: ":floppy_disk: publish image"
    command: ".buildkite/steps/publish-image.sh"
    if: |
        build.branch =~ /^(master|develop|^ci-.+|v[0-9]+\.[0-9]+\..+)$$/ &&
        (build.env("NEON_EVM_BRANCH") == "develop" || build.env("NEON_EVM_BRANCH") == null)


