steps:
  - label: ":docker: build docker image"
    command:
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

  - label: ":terraform: build infrastructure"
    key: "create_infrastructure"
    if: &is_fts_enabled |
        (build.pull_request.base_branch == "develop" && !build.pull_request.draft) ||
        (build.source == "trigger_job" && build.env("NEON_EVM_FULL_TEST_SUITE") == "true")
    agents:
      queue: "testing"
    command:
      - ".buildkite/steps/full_test_suite/terraform-build.sh"

  - label: ":cop::skin-tone-2: deploy check"
    command: ".buildkite/steps/deploy-test.sh"
    timeout: 90
    agents:
       queue: "testing"
    artifact_paths:
      - "proxy.log"
      - "solana.log"
      - "measurements.log"
      - "dbcreation.log"
      - "faucet.log"
      - "airdropper.log"
      - "indexer.log"
      - "deploy_contracts.log"
      - "proxy_program_loader.log"
#    env:
#      UNITTEST_TESTNAME: indexer_work

  - label: ":coverage: full test suite (FTS)"
    key: "full_test_suite"
    if: *is_fts_enabled
    commands:
      - ".buildkite/steps/full_test_suite/run_full_test_suite.sh"
    env:
      FTS_THRESHOLD: 1920
      FTS_CONTAINER_NAME: fts_${BUILDKITE_BUILD_NUMBER}
      FTS_IMAGE: neonlabsorg/full_test_suite:develop
      FTS_USERS_NUMBER: 15
      FTS_JOBS_NUMBER: 8
      NETWORK_NAME: full-test-suite-${BUILDKITE_BUILD_NUMBER}
      NETWORK_ID: 111
      REQUEST_AMOUNT: 20000
      USE_FAUCET: true
    agents:
       queue: "testing"
    artifact_paths:
      - allure-reports.tar.gz
      - fts_${BUILDKITE_BUILD_NUMBER}.log
      - "./logs/*"
    depends_on: "create_infrastructure"

  - wait

  - label: ":floppy_disk: publish image"
    command: ".buildkite/steps/publish-image.sh"
    if: |
        build.branch =~ /^(master|develop|^ci-.+|v[0-9]+\.[0-9]+\..+)$$/ &&
        (build.env("NEON_EVM_BRANCH") == "develop" || build.env("NEON_EVM_BRANCH") == null)

  - label: ":terraform: destroy infrastructure"
    agents:
      queue: "testing"
    if: *is_fts_enabled
    command:
      - ".buildkite/steps/full_test_suite/terraform-destroy.sh"
    depends_on:
      - "full_test_suite"
      - "create_infrastructure"
    allow_dependency_failure: true


