version: "3"

services:

  full_test_suite:
    container_name: ${FTS_CONTAINER_NAME:-full_test_suite}
    image: ${FTS_IMAGE:-neonlabsorg/develop}
    entrypoint: ./run-test.sh 2>/dev/null
    environment:
      - SOLANA_EXPLORER=https://explorer.solana.com/?cluster=custom&customUrl=http://proxy.night.stand.neontest.xyz/node-solana
      - NETWORK_NAME=${NETWORK_NAME}
      - PROXY_URL=${PROXY_URL}
      - NETWORK_ID=${NETWORK_ID}
      - REQUEST_AMOUNT=${REQUEST_AMOUNT}
      - FAUCET_URL=${FAUCET_URL}
      - USE_FAUCET=${USE_FAUCET}
      - SOLANA_URL=${SOLANA_URL}
      - USERS_NUMBER=${USERS_NUMBER}
      - JOBS_NUMBER=${JOBS_NUMBER}
    network_mode: host
