from solana.publickey import PublicKey

from .common_neon.elf_params import read_elf_params

ELF_PARAMS = {}
read_elf_params(ELF_PARAMS)
HOLDER_MSG_SIZE = int(ELF_PARAMS.get("NEON_HOLDER_MSG_SIZE"))
NEON_EVM_VERSION = ELF_PARAMS.get("NEON_PKG_VERSION")
NEON_EVM_REVISION = ELF_PARAMS.get('NEON_REVISION')
NEON_COMPUTE_UNITS = int(ELF_PARAMS.get('NEON_COMPUTE_UNITS'))
NEON_HEAP_FRAME = int(ELF_PARAMS.get('NEON_HEAP_FRAME'))
NEON_ADDITIONAL_FEE = int(ELF_PARAMS.get('NEON_ADDITIONAL_FEE'))
NEON_GAS_LIMIT_MULTIPLIER_NO_CHAINID = int(ELF_PARAMS.get('NEON_GAS_LIMIT_MULTIPLIER_NO_CHAINID'))
